version: '3.7'

services:

  node-server:
    build: docker/node-server
    command: yarn --cwd "./server/" run-server
    ports:
      - 80:8082
    volumes:
      - .:/app/

  node-browser:
    build: docker/node-browser
    command: yarn --cwd "./browser" build
    links:
      - node-server
    ports:
      - 8080:8080
    volumes:
      - .:/app/